import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-help-menu',
  templateUrl: './help-menu.component.html',
  styleUrls: ['./help-menu.component.css']
})
export class HelpMenuComponent implements OnInit {
  sections = [
    {
      title: "Customer",
      chapters: [
        {
          title: "How to log in",
          content: [
            "1. Press log in on the top navbar",
            "2. Input username",
            "3. Input password",
            "4. Press log in"
          ]
        }, {
          title: "How to book a One Way/Round Trip flight",
          content: [
            "1. Press FlightBook logo",
            "2. Select One Way/Round Trip",
            "3. Fill in all parameters",
            "4. Press search",
            "5. Book desired flight"
          ]
        }, {
          title: "How to book a Multi-City",
          content: [
            "1. Press FlightBook logo",
            "2. Select Multi-City",
            "3. Add or delete desired number of flights",
            "4. Fill in all parameters",
            "5. Press search",
            "6. Book desired flight"
          ]
        }, {
          title: "View Past and Current Reservations",
          content: [
            "1. Press the dropdown menu on top right of the navbar",
            "2. Select reservations",
            "3. View the legs of your reservation by pressing the plus", 
          ]
        }, {
          title: "Bid history of flights",
          content: [
            "1. Under dashboard, press Bids",
            "2. View Auctions made in the past"
          ]
        }, {
          title: "View Customer Information",
          content: [
            "1. Press the top right icon with your name",
            "2. Press profile"
          ]
        }, {
          title: "View Travel Itinerary For a Given Reservation",
          content: [
            "1. View your Past and Current Reservations",
            "2. Press the plus sign next to one of the reservations"
          ]
        }
      ]
    }, {
      title: "Customer Representative",
      chapters: [
        {
          title: "How to log in",
          content: [
            "1. Press log in on the top navbar",
            "2. Input username",
            "3. Input password",
            "4. Press log in"
          ]
        }, {
          title: "Record a Reservation For a Customer",
          content: [
            "1. Go through the flight searching process",
            "2. Click Reserve for Customer at the checkout screen"
          ]
        }, {
          title: "Observe Mailing List",
          content: [
            "1. Go to your dashboard and go to customers",
            "2. Scroll down to mailing list to observe customer mailing lists"
          ]
        }, {
          title: "Create a Customer",
          content: [
            "1. Go to Dashboard and go to the Customers Tab",
            "2. Press Create Customer and fill in information needed"
          ]
        }, {
          title: "Get Suggested Flight for a Customer",
          content: [
            "1. Go to Dashboard and go to the Customers Tab",
            "2. Scroll down to Suggested Flights card and input Account Number",
            "3. Hit Get Suggestions and observe the queried suggestion"
          ]
        }
      ]
    }, {
      title: "Manager",
      chapters: [
        {
          title: "How to log in",
          content: [
            "1. Press log in on the top navbar",
            "2. Input username",
            "3. Input password",
            "4. Press log in"
          ]
        },{
          title: "Record a Reservation For a Customer",
          content: [
            "1. Go through the flight searching process",
            "2. Click Reserve for Customer at the checkout screen"
          ]
        }, {
          title: "Observe Listing of All Flights",
          content: [
            "1. Go to Dashboard and go to Flights",
            "2. Observe flights"
          ]
        }, {
          title: "Add Flight",
          content: [
            "1. Go to Dashboard and go to tab Flights",
            "2. Fill in parameters and add flight"
          ]
        }, {
          title: "Create an Employee",
          content: [
            "1. Go to Dashboard and go to Employees Tab",
            "2. Press Create Employee",
            "3. Fill in Parameters and add new employee"
          ]
        }, {
          title: "Produce a Summary Listing of Revenue Generated by a Particular Flight, Destination City, or Customer",
          content: [
            "1. Go to Dashboard and go to Revenue Tab",
            "2. Filter the Revenue by what you want and then submit it",
            "3. Observe revenue given by filter"
          ]
        }, {
          title: "Best Customer Representative by Revenue Generated",
          content: [
            "1. Go to your Dashboard under Revenue Tab",
            "2. Scroll to the Revenue by Best Employee and observe the ID of best Employee"
          ]
        }, {
          title: "Best Customer by Revenue Generated",
          content: [
            "1. Go to Revenue Tab",
            "2. Scroll down to Revenue by Best Customer and observe ID"
          ]
        }, { 
          title: "List of Most Active Flights",
          content:[
            "1. Go to Flights Tab",
            "2. Scroll down to Most Frequent Flights"
          ]
        }, {
          title: "Find Flights by Airport",
          content: [
            "1. Go to FLights Tab",
            "2. Scroll down to Find Flights by Airport",
            "3. Enter Airport Id and get Flights"
          ]
        }, {
          title: "Observe Customer on Flight",
          content: [
            "1. Go to Flights Tab",
            "2. Scroll down to Customer on Flight",
            "3. Enter Flight No and Airline Id press Get Customer",
            "4. Observe customers on flight"
          ]
        }, {
          title: "Filter Reservation by Reservation Number, Flight, Account Number and Name",
          content: [
            "1. Go to Reservations Tab",
            "2. Select what you want to filter by",
            "3. Submit information and see the queried Reservations"
          ]
        }
      ]
    }
  ];

  

  constructor() { }

  ngOnInit() {
  }

}
